[package]
name = "polkapipe"
description = "Fork of sube focusing on communication"
license = "Apache-2.0"
version = "0.5.1"
authors = ["Daniel Olano <daniel@olanod.com>"]
edition = "2018"
repository = "https://github.com/valibre-org/sube"

[dependencies]
async-trait = "0.1.51"
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
log = "0.4.14"
jsonrpc = { version = "0.12.0", default-features = false }
serde_json = { version = "1.0", default-features = false }

# http backend
surf = { version = "2.3.1", default_features = false, optional = true }

# ws backend
async-tungstenite = { version = "0.15.0",  default-features = false, features = ["async-std-runtime"], optional = true }
futures-channel = { version = "0.3.17", default-features = false, features = ["alloc"], optional = true }
futures-util = { version = "0.3.17", default-features = false, features = ["sink"], optional = true }
async-mutex = { version = "1.4.0", optional = true }
async-tls = { version = "0.11.0", default-features = false, optional = true }
async-std = { version = "1.10.0", default_features = false, optional = true }

[dev-dependencies]
async-std = { version = "1.10.0", features = ["attributes"] }
hex-literal = "0.3.3"
env_logger = "*"

[features]
default = ["std", "ws"]
http = ["surf/h1-client-rustls"]
http-web = ["surf/wasm-client"]
std = []
ws = ["async-std", "async-tungstenite", "async-mutex", "futures-util", "futures-channel"]
wss = ["ws", "async-tls", "async-tungstenite/async-tls"]


[package.metadata.docs.rs]
features = ["http"]
