name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Run tests ws
      run: cargo test --verbose
    - name: Run tests wss
      run: cargo test --verbose --features wss
    - name: Run tests http
      run: cargo test --verbose --features http
    - name: Run tests smoldot desktop
      run: cargo test --release --verbose --features smoldot-std
  browser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: add target
      run: rustup target add wasm32-unknown-unknown
    - name: check http-web
      run: cargo check --verbose --features http-web --target wasm32-unknown-unknown
    - name: check ws-web
      run: wasm-pack test --headless --firefox --no-default-features --features ws-web