name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Run tests ws
      run: cargo test --locked --verbose
    - name: Run tests wss
      run: cargo test --locked --verbose --features wss
    - name: Run tests smoldot desktop
      run: cargo test --locked --verbose --features smoldot-std
    - name: Run tests http
      run: cargo test --locked --verbose --features http
  browser:
    - name: check http-web
      run: cargo check --locked --verbose --features http-web --target wasm32-unknown-unknown
    - name: check ws-web
      run: cargo check --locked --verbose --features ws-web --target wasm32-unknown-unknown